### ISSUE TITLE
An error of function "adhocGene.TabulateExpression.PSI.10X"

### ISSUE THREAD

**Issue by ksbb1853223** [wenweixiong/MARVEL#13]
Dear wenweixiong:
I used Marvel to analyze "ADCY7" genes.The function” adhocgene.tabulateexpression.10x“ worked fine. But there was an error when using the function "adhocGene.TabulateExpression.PSI.10X".The error message is ”Error in aggregate.data.frame(as.data.frame(x), ...) : 
  no rows to aggregate“.

The code comes from the official site guide, and I only changed the gene name and min.pct.cells.
marvel <- adhocGene.TabulateExpression.Gene.10x(MarvelObject=marvel,
                                                cell.group.list=cell.group.list,
                                                gene_short_name="ADCY7",
                                                min.pct.cells = 1)
marvel <- adhocGene.TabulateExpression.PSI.10x(MarvelObject=marvel,
                                               min.pct.cells=1)

When I replace Adcy7 with S100A8, the error disappears. And how to resolve ADCY7 encountered errors.
 Thanks!

**Comment by ksbb1853223** [comment]
I re-adjusted the ”min.pct.cells“ values and it worked fine

**Comment by wenweixiong** [comment]
ADCY7 was probably a very lowly-expressed gene, i.e. expressed in <1% of the cells of your dataset.
