### ISSUE TITLE
Issues ComputePsi

### ISSUE THREAD

**Issue by TdzBAS** [wenweixiong/MARVEL#17]
Hi Sean,

Thank you for your amazing tool. I have a dataset and have applied your pipeline from (https://wenweixiong.github.io/MARVEL_Plate.html). However, I'm encountering issues with the computepsi functions. The coordinates of the splice junctions are different. For the skipped exon case, you previously helped me by removing the minus 1 in the assignment of the end variable, and everything worked perfectly.

But for the other 4 common AS types, I haven't been able to implement it successfully.

I understand that the intron count matrix is still missing for retained introns. But would be awesome if you can help me out with the other splicing types.

I provided you the input files and my code. The marvel-object would be too big, since i used the whole human gtf file from gencode v43.

Thank you in advance for your assistance!

Best regards,
Tolga
[marvel_test.zip](https://github.com/wenweixiong/MARVEL/files/11848807/marvel_test.zip)

**Comment by wenweixiong** [comment]
Hi Tolga,

Please may you share the original output files from rMATS, i.e., the fromGTF.SE.txt, fromGTF.MXE.txt, fromGTF.RI.txt, fromGTF.A5SS.txt, fromGTF.A3SS.txt please?

Sean

**Comment by TdzBAS** [comment]
Hi Sean,

sure!
I see that i did not used transcriptome.bam, but gene.bam.

Best,
Tolga
[fromGTF.A3SS.txt](https://github.com/wenweixiong/MARVEL/files/11904139/fromGTF.A3SS.txt)
[fromGTF.A5SS.txt](https://github.com/wenweixiong/MARVEL/files/11904141/fromGTF.A5SS.txt)
[fromGTF.MXE.txt](https://github.com/wenweixiong/MARVEL/files/11904143/fromGTF.MXE.txt)
[fromGTF.RI.txt](https://github.com/wenweixiong/MARVEL/files/11904144/fromGTF.RI.txt)
[fromGTF.SE.txt](https://github.com/wenweixiong/MARVEL/files/11904145/fromGTF.SE.txt)

**Comment by wenweixiong** [comment]
rMATS files look good Tolga.

I have updated MARVEL with functions to process the rMATS coordinates (fromGTF.SE.txt,  fromGTF.MXE.txt, fromGTF.RI.txt, fromGTF.A5SS.txt, fromGTF.A3SS.txt file) into MARVEL splicing event metadata (SE_featureData.txt, MXE_featureData.txt, RI_featureData.txt, A5SS_featureData.txt, A3SS_featureData.txt). These files may be used directly for "Splicing event metadata" section of the tutorial (https://wenweixiong.github.io/MARVEL_Plate.html)

Please may you install the latest version of MARVEL from Github to access these functions (v2.0.4, https://github.com/wenweixiong/MARVEL). 

And then download the example data and script from Google Drive (https://drive.google.com/file/d/1ilhgUdRQYC2ee1fbA54ZdxbbtB8tlQ2m/view?usp=sharing). 

Further reading under section v2.0.4 on Github (https://github.com/wenweixiong/MARVEL)

**Comment by wenweixiong** [comment]
I fixed a typo in the function in v2.0.4 a few weeks back. Please may you *re-install* v2.0.4?

library(devtools)
install_github("wenweixiong/MARVEL")
library(MARVEL)

The Preprocess_rMATS() should then become available...

<img width="939" alt="Screenshot 2023-06-30 at 04 20 01" src="https://github.com/wenweixiong/MARVEL/assets/45239277/2a175652-3fd8-4c47-87b1-31855755a39a">

**Comment by TdzBAS** [comment]
Hi Sean,

Thanks for this very nice update! All preprocessing functions are working without an error. 
Now I want to add the retained introns part. For this you also provided some scripts, but where do I get the GRCh38.primary_assembly.genome_bedtools.txt? I am not familiar with bedtools. 

Best,
Tolga

**Comment by wenweixiong** [comment]
Hi Tolga,

The GRCh38.primary_assembly.genome_bedtools.txt is a tab-delimited file indicating the size of each chromosome. The 1st column is the chromosome name, and the 2nd column is the size in bp. The example attached is for hg38 build and for chr1-22, X, Y, and M: 
[hg38.chrom.sizes_edit.txt](https://github.com/wenweixiong/MARVEL/files/11946982/hg38.chrom.sizes_edit.txt)

To be safe, you may run the following Samtools code to generate your own chromosome size file:

samtools faidx input.fa
cut -f1,2 input.fa.fai > sizes.genome

You may skip 1st line if you have already generated index file (.fai)

Sean

**Comment by TdzBAS** [comment]
Hi Sean,

big thanks! This was the missing piece. I will get it up running. Will keep you updated :)

Best,
Tolga

**Comment by wenweixiong** [comment]
Excellent! These are genomic sequences that we're unsure which chromosomes they map to. Given that my and your list of chromosomes are different, you should use your list for the bedtools step so that it tallies with your reference genome file.

**Comment by TdzBAS** [comment]
Hi @sean,

Just wanted to tell you, that everything went perfectly fine! Thanks for updating the MARVEL-package with this convenient new functions!

Best,
Tolga
