### ISSUE TITLE
Seurat object integration

### ISSUE THREAD

**Issue by LacquerHed** [wenweixiong/MARVEL#19]
Hi, thank you for this great package! I am wondering if there is an easy way or wrapper for using a Seurat object in the MARVEL analysis?

**Comment by wenweixiong** [comment]
Hi, unfortunately MARVEL doesn't have functions for Seurat object. But you may perform your usual cell QC, gene expression normalisation, and clustering analysis, and then export the relevant files into MARVEL for splicing and gene expression analysis, e.g., raw gene count matrix, normalised gene expression matrix, and UMAP/tSNE coordinates.

**Comment by guptas2005** [comment]
@wenweixiong just wondering if MARVEL has been updated to include Seurat integration?
