### ISSUE TITLE
github package installation error

### ISSUE THREAD

**Issue by Guangsheng357** [wenweixiong/MARVEL#20]
Hi,
I'm trying to install MARVEL from github by install_github("wenweixiong/MARVEL"), and it gives an error like following. Do you have any suggestions about this error?
* installing *source* package ‘MARVEL’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘MARVEL’ in namespaceExport(ns, exports):
 undefined exports: ElbowPlot
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/MARVEL’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/ts/d10fg4gs5jlgz0mts4sktsbjb5m41s/T//RtmprMVzfs/file574a2d518b01/MARVEL_2.0.4.tar.gz’ had non-zero exit status

**Comment by wenweixiong** [comment]
My bad, I made a blunder when updating the MARVEL package on Github earlier this week. I have fixed this, please try to install again?
