### ISSUE TITLE
Error in AnnotateGenes.10x function

### ISSUE THREAD

**Issue by Rahul1711arora** [wenweixiong/MARVEL#22]
Hi, 

I have been trying to use the function `AnnotateGenes.10x(MarvelObject=marvel)` but upon running this, I get an error message: `Error in strsplit(gtf$V9, split = ";") : non-character argument`. At the 9th index, I initially checked the class of the column which was integer. I then changed it to character but the error message still persists. 
The steps before this runs well. 

Hope this can be answered soon. Thanks in advance for all the help.

**Comment by wenweixiong** [comment]
May you share your R object after CreateMarvelObject.10x step please?

**Comment by Rahul1711arora** [comment]
Hi, I tried to attach the zip file for the R object but unfortunately it's 120MB and can't be added. Do you know of an alternative of how can I share the object with you? Thanks, R

**Comment by Rahul1711arora** [comment]
Hi, so as I stated previously that I have re-written this function so I no longer get that error message but I get the same error upon running `AnnotateSJ.10x`. I really don't want to rewrite these functions again as you have already done the leg work. If you think there's a way around, then it would be very helpful.

**Comment by Rahul1711arora** [comment]
Hi Sean, 

Thanks for your response. After identifying the parameters to change based on the headers in my GTF and also the tab separated values, I was able to run the `AnnotateGenes.10x` and `AnnotateSJ.10x` functions easily. 
Now, when I run the next functions, like `ValidateSJ.10x` and `FilterGenes.10x`, I get the following outputs: 

`marvel <- AnnotateSJ.10x(MarvelObject=marvel)`


```
Creating splice junction metadata...
Parsing GTF...
Matching gene names with SJ start coordinates in GTF...
Matching gene names with SJ end coordinates in GTF...
Annotating splice junctions...
All SJ successfully annotated
```

`marvel_valid_SJ <- ValidateSJ.10x(MarvelObject=marvel)`

```
443344 unannotated SJ identified
SJ metadata and SJ count matrix updated
```

`marvel_filter <- FilterGenes.10x(MarvelObject=marvel, gene.type="protein_coding")
`

```
0 of 19257 genes met filtering criteria and retained
0 of 443344 SJ met filtering criteria and retained
Normalised gene and SJ metadata and matrix updated
```

Could you please suggest how to get around this? I don't think I would be able to change the GTF at this stage as it has been used for mapping in STARsolo for all the samples and this is the same file that our collaborators are also using. So, we need to  use this file in order to maintain the consistency. 

Your assistance would be very helpful. 

Best,
Rahul

**Comment by wenweixiong** [comment]
Hi Rahul,

May you share your R object after CreateMarvelObject.10x step please?

Sean

**Comment by Rahul1711arora** [comment]
Hi Sean, 

Thanks for your prompt response. I have shared the marvel object and it has been run through the `AnnotateSJ.10x` function.

**Comment by wenweixiong** [comment]
It would seem the resulting table `marvel$sj.metadata` from the `AnnotateSJ.10x` is empty in `marvel_RA.rds`. Anyhow, I think renaming the column `gene_biotype` to `gene_type` may fix the error you encountered at `FilterGenes.10x`. 

Something like:

```
gene.metadata <- marvel$gene.metadata
names(gene.metadata)[2] <- "gene_type"
head(gene.metadata)
marvel$gene.metadata <- gene.metadata
```

Please see "Annotate gene metadata" of the tutorial https://wenweixiong.github.io/MARVEL_Droplet.html

<img width="864" alt="Screenshot 2023-08-28 at 20 58 26" src="https://github.com/wenweixiong/MARVEL/assets/45239277/e6dab178-eb73-49e0-b1fc-1d52f7e13527">

**Comment by Rahul1711arora** [comment]
Hi Sean, 

Thanks for responding. 
I tried to use the fix as you suggested. It did help to filter the protein coding genes. But I believe the problem is more deeper. When I run the `AnnotateSJ.10x`, I get the message at the end `All SJ annotated successfully`. Which makes sense because all the rows in the column `sj.type` are populated. But what remained empty were the columns `gene_short_name.start ` and  `gene_short_name.end`.  I realised that it's the join function that doesn't work and I had to change it to merge. And now the functions work. 

I will suggest you that since I also checked a few more GTFs and found out that they all had the same format like the one I'm using, perhaps you can add a line to your tutorial that if someone is using a GTF with this structure, then they might need to either modify the functions a bit or their GTF to be compatible. Cheers.

**Comment by mattzano** [comment]
Hi Sean and Rahul,

I think what can help for the AnnotateGenes.10X function is to change line 14 and 15 
```
 . <- sapply(., function(x) grep("gene_biotype", x, value = TRUE))
  . <- gsub("gene_biotype", "", .)
```

to 
```
. <- sapply(., function(x) grep("gene_type", x, value = TRUE))
  . <- gsub("gene_type", "", .)
```
  
At least the gtf I'm using use gene_type instead of gene_biotype
This would also avoid the necessity to fix the colnames in order to run FilterGenes.10x

**Comment by wenweixiong** [comment]
I think the ```AnnotateGenes.10x``` already accommodate to both ```gene_type``` and ```gene_biotype``` annotations:

```
# gene type
        . <- strsplit(gtf$V9, split=";")
        . <- sapply(., function(x) grep("gene_biotype", x, value=TRUE))
        . <- gsub("gene_biotype", "", .)
        . <- gsub(" ", "", .)
        . <- gsub("\"", "", .)
            
        if(.[1] == "character(0)") {
            
            . <- strsplit(gtf$V9, split=";")
            . <- sapply(., function(x) grep("gene_type", x, value=TRUE))
            . <- gsub("gene_type", "", .)
            . <- gsub(" ", "", .)
            . <- gsub("\"", "", .)
            
        }

        gtf$gene_type <- .
```

The probable issue here is that the function currently accommodate GTF in its conventional format (example below), but not for other types of GTF format.

![image](https://github.com/wenweixiong/MARVEL/assets/45239277/0d1d0299-a9ee-4e5c-a2c4-fbd7681484e2)
