### ISSUE TITLE
Error in adhocGene.PlotSJPosition.10x function. 

### ISSUE THREAD

**Issue by JFerrer-B** [wenweixiong/MARVEL#23]
I have a problem running the function adhocGene.PlotSJPosition.10x. I share the error message.

`marvel <- adhocGene.PlotSJPosition.10x(MarvelObject=marvel,
                                       coord.intron=coord.intron,
                                       rescale_introns=TRUE,
                                       show.protein.coding.only=TRUE,
                                       anno.label.size=1.5)`

Retrieving transcripts from GTF file...
9 transcripts identified
Error in wiggleplotr::plotTranscripts(exons = grange.exon.list, cdss = grange.cds.list,  : 
  unused arguments (anno.colors = anno.colors, anno.label.size = anno.label.size)

I hope you can help me with this. This function provides very useful pictures.
Thanks in advance for your help.
Juan

**Comment by wenweixiong** [comment]
Hi,

Please download the modified wiggleplotr package from here: http://datashare.molbiol.ox.ac.uk/public/project/meadlab/wwen/wiggleplotr_1.18.0.tar.gz

And then install the package with: install.packages("wiggleplotr_1.18.0.tar.gz", repos=NULL, type="source")

This wiggleplotr package has been modified from the original CRAN version and should contain the arguments anno.colors and anno.label.size

Sean
