### ISSUE TITLE
Aggregate figures issue

### ISSUE THREAD

**Issue by JFerrer-B** [wenweixiong/MARVEL#24]
The adhocGene.PlotSJPosition.10x function only accepts a coord.intron as input.
However, in the tutorial (https://wenweixiong.github.io/MARVEL_Droplet.html#Candidate_gene_analysis) you can see in the last figure that there is an image of the transcriptome with several junctions at the same time.
Is there a function for this picture?

![image](https://github.com/wenweixiong/MARVEL/assets/38467620/b9c9a5ad-e552-4d29-b752-e218e0698e9e)

**Comment by wenweixiong** [comment]
Indeed the ```adhocGene.PlotSJPosition.10x``` function only plot one splice junction at a time. After generating the individual splice junction plots, we would have to merge them and perform other edits, e.g., customise the colours, manually in PowerPoint, Adobe etc..
