### ISSUE TITLE
Error in strsplit splice junction annotation

### ISSUE THREAD

**Issue by LacquerHed** [wenweixiong/MARVEL#26]
Hi getting the following error when running this portion of tutorial of test data:

`marvel <- AnnotateSJ.10x(MarvelObject=marvel)`

`Creating splice junction metadata...
Error in strsplit(rownames(df.sj.count), split = ":", fixed = TRUE) : 
  non-character argument`

Thanks!

**Comment by wenweixiong** [comment]
I think the issue lies with the newer format of GTF. I would need to update the function to accommodate the newer format of GTF. Please may you share your MARVEL object after the running the CreateMarvelObject.10x function please? Here or my email (sean.wen@astrazeneca.com) will be fine.

**Comment by LacquerHed** [comment]
Actually I believe I just adjusted the function to account for GTF:

Previously: `strsplit(rownames(df.sj.count), split = ":", fixed = TRUE)`

Changed to: `strsplit(as.character(df.sj.count), split = ";", fixed = TRUE)`

Seems to be running now, does this seem like the correct adjustment?

Here is a snipped of the GTF:

                                                                                                                                                                                                                                                           
`1  gene_id "ENSG00000243485"; gene_version "5"; gene_name "MIR1302-2HG"; gene_source "havana"`

**Comment by wenweixiong** [comment]
I see that the splice junction coordinates are missing from the splice junction count matrix.

<img width="952" alt="Screenshot 2023-10-26 at 13 16 38" src="https://github.com/wenweixiong/MARVEL/assets/45239277/7ee8a484-0fa7-4f2c-b3b3-3bf4d6281a7e">

am wondering if the splice junction coordinate file (`featureData.txt`) was formatted as per the tutorial (see "Splice junction counts" section), and was subsequently specified with the `sj.count.feature` option of the `CreateMarvelObject.10x` function (see "Create MARVEL object" section)?
