### ISSUE TITLE
0 of 0 SJ met filtering criteria and retained

### ISSUE THREAD

**Issue by trianaptx** [wenweixiong/MARVEL#28]
head(marvel$sj.metadata)
   coord.intron gene_short_name.start gene_short_name.end                             sj.type
1 1:10078:10178                  <NA>                <NA> start_unknown.gene|end_unknown.gene
2 1:10084:10178                  <NA>                <NA> start_unknown.gene|end_unknown.gene
3 1:10090:10178                  <NA>                <NA> start_unknown.gene|end_unknown.gene
4 1:10096:10178                  <NA>                <NA> start_unknown.gene|end_unknown.gene
5 1:10102:10178                  <NA>                <NA> start_unknown.gene|end_unknown.gene
6 1:10896:10969                  <NA>                <NA> start_unknown.gene|end_unknown.gene

> marvel <- ValidateSJ.10x(MarvelObject=marvel)  #同一基因
500462 unannotated SJ identified
SJ metadata and SJ count matrix updated
> head(marvel$sj.metadata)
[1] coord.intron          gene_short_name.start gene_short_name.end   sj.type              
<0 rows> (or 0-length row.names)

hello, could you please tell me what wrong with it, is it a problem of gtf file, or their is some thing wrong in the process of STARsolo? I can run this function normaly previous,but these days I came this bug.Thank you very much if you can address this.

**Comment by wenweixiong** [comment]
I believe the issue is with the GTF file, I may need to update the function to accommodate the newer format of GTF. May you share your R object here or my work email (sean.wen@astrazeneca.com) after running `CreateMarvelObject.10x` function please?

**Comment by trianaptx** [comment]
Sure，but I will use the Gmail，with a link of Google Drive in that email.发自我的手机-------- 原始邮件 --------发件人： Sean Wen ***@***.***>日期： 2023年10月26日周四 晚上8:29收件人： wenweixiong/MARVEL ***@***.***>抄送： trianaptx ***@***.***>, Author ***@***.***>主    题： Re: [wenweixiong/MARVEL] 0 of 0 SJ met filtering criteria and retained (Issue #28)
I believe the issue is with the GTF file, I may need to update the function to accommodate the newer format of GTF. May you share your R object here or my work email ***@***.***) after running CreateMarvelObject.10x function please?

**Comment by trianaptx** [comment]
Thank you very much!!!
