### ISSUE TITLE
How to annotate AS events on the droplet-based platform?

### ISSUE THREAD

**Issue by ZehangJiang** [wenweixiong/MARVEL#29]
Hi, I used the droplet-based methods (https://wenweixiong.github.io/MARVEL_Droplet.html) to identify alternative splicing events, but I noticed that the annotated alternative splicing types are mainly (coordinated/opposing/iso-switch/complex), rather than the expected types (SE/MXE/RI/A5SS/A3SS). Could you please provide guidance on how to address this issue?

**Comment by wenweixiong** [comment]
Droplet-based method detects splicing events at the splice junction level, and therefore, does not detect splicing events at the exon-level (SE/MXE/RI/A5SS/A3SS). Exon-level splicing analysis is only applicable for plate-based methods, e.g., Smart-seq2.

The categories coordinated/opposing/iso-switch/complex reflect the relationship between gene expression and splicing, these categories do not reflect the different types of splicing events.

Please refer to https://academic.oup.com/nar/article/51/5/e29/6985826?login=false for further clarification.
