### ISSUE TITLE
does the 10

### ISSUE THREAD

**Issue by CCCBBG** [wenweixiong/MARVEL#31]
Can Nonsense-mediated decay (NMD) prediction analysis be performed with 10x Genomics data？

**Comment by wenweixiong** [comment]
NMD prediction is only applicable for exon-level splicing analysis, i.e., plate-based. Unfortunately, MARVEL doesn't predict NMD for splice junction-level splicing analysis, i.e., 10x Genomics..

**Comment by CCCBBG** [comment]
thanks a lot
