### ISSUE TITLE
all Gene-splicing dynamics is ISO-switch

### ISSUE THREAD

**Issue by trianaptx** [wenweixiong/MARVEL#32]
hello,professor,I use the droplet scRNA-seq analysis part to process my data and my sample is human HSC.Most of the subpopulation of my sample does not has differentail gene,but has differentail sj, is it a normal phenomanen?

**Comment by wenweixiong** [comment]
Admittedly, the approach to detect differentially spliced junctions (permutation test) is more lenient than the approach to detect differentially expressed genes (Wilcox test + adjusting for multiple testing). I would be cautions about interpreting your results in this case given no differentially expressed genes were found. I would recommend double checking the upstream data processing steps including cell type annotation, sample size (were there sufficient cells in cell group 1 and 2?) etc..

**Comment by trianaptx** [comment]
Okay，thank you very much.I will try what you said.












虚云
***@***.***






---Original---
From: "Sean ***@***.***&gt;
Date: Thu, Jan 4, 2024 22:53 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [wenweixiong/MARVEL] all Gene-splicing dynamics is ISO-switch(Issue #32)




 
Admittedly, the approach to detect differentially spliced junctions (permutation test) is more lenient than the approach to detect differentially expressed genes (Wilcox test + adjusting for multiple testing). I would be cautions about interpreting your results in this case given no differentially expressed genes were found. I would recommend double checking the upstream data processing steps including cell type annotation, sample size (were there sufficient cells in cell group 1 and 2?) etc..
