### ISSUE TITLE
how to understand the differential splicing analysis result

### ISSUE THREAD

**Issue by Guangsheng357** [wenweixiong/MARVEL#35]
Hi,

Thank you for this wonderful tools. I have some confusion about the differential splicing result. In the result, there are columns named "mean.g1", "mean.g2", "mean.diff".  Could you help explaining the meaning of these columns. I am wondering how I can know which splicing event is biased to which group. Does high group mean value mean the splicing event is biased to that group? Could I use the group mean value column to calculate fold change and plot the volcano plot?  For the last column "outliers", should I just consider the splicing event that "outliers" = FALSE? If I want to select the significant splicing event, should I use "p.val" or "p.val.adj" to filter the event.  Additionally, when we use two methods (ad, dts) in differentially splicing analysis, could we simply merged the results from these two methods together? Thanks for the help.

**Comment by wenweixiong** [comment]
`mean.g1` and `mean.g2` columns refer to the mean PSI of cell groups specified in `cell.group.g1` and `cell.group.g2` option, respectively, of the `CompareValues` function. 

`mean.diff` = mean.g2 minus mean.g1. Therefore, mean.diff is the difference in PSI value in `cell.group.g2` relative to `cell.group.g1`.

Yes, you may derive fold change from the `mean.g1` and `mean.g2` columns, and generate the volcano plot.

Yes, you should only consider non-outliers, i.e., `FALSE` under `outliers` column.

For defining significant splicing events, you may either use `p.val` or `p.val.adj` columns when DTS statistical test was used. But you should only refer to `p.val.adj` column when other statistical tests, including AD, were used. For simplicity, I would recommend using DTS only as this method captures majority of differentially spliced events, including those detected by AD or other statistical tests.

**Comment by Guangsheng357** [comment]
Thank you so much!
