### ISSUE TITLE
MARVEL for 30000+cells from ICELL8 platform

### ISSUE THREAD

**Issue by caochch** [wenweixiong/MARVEL#38]
Dear,

I used the ICELL8 scRNA-seq platform and sequenced ~30000 cells, with each cell having 10^6 reads.
Which strategy do you suggest to quantify the splicing junction count for my scRNAseq data?  
Of note, ICELL8 is a plated-based platform.

Looking forward to your reply
Best wishes
Changchang Cao

**Comment by wenweixiong** [comment]
Given that it's plate-based platform and high depth sequencing (10 ^ 6 = 1,000,000 reads per cell), I would recommend using the plate-based approach for splicing analysis.

**Comment by caochch** [comment]
That will be a huge project, running STAR for 30000 times to count splice junction reads

**Comment by wenweixiong** [comment]
You may run STARsolo on the master BAM file (consisting of all cells, similar to cellranger's possorted_genome_bam.bam) to obtain the splice junction x cell matrix, and then further format the matrix for MARVEL's plate-based analysis.

**Comment by caochch** [comment]
Thanks a lot for this help.
Best wishes.
