### ISSUE TITLE
wiggelplotr: wrong version ?

### ISSUE THREAD

**Issue by Romeo1-1** [wenweixiong/MARVEL#4]
Hello,

Thank you again for this very useful package ! I am exploring the functionalities offered by your pacakge in my datasets.

I have an issue with adhocGene.PlotSJPosition.10x function, at the very end. For now, everything else seems to work fine.

When i

```
marvel <- adhocGene.PlotSJPosition.10x(MarvelObject=marvel,
                                       coord.intron=xxx,
                                       rescale_introns=FALSE,
                                       show.protein.coding.only=TRUE,
                                       anno.label.size=1.5)
```
I get the error that  `anno.colors=anno.colors & anno.label.size=anno.label.size are unused arguments`

If I modify the adhocGene.PlotSJPosition.10x script to take out these 2 arguments, then I get a different image than the tutorial, without any annotations or color.

To install wiggleplotr, i used your modified version (http://datashare.molbiol.ox.ac.uk/public/wwen/wiggleplotr_1.18.0_master.tar.gz) with the `install.packages("wiggleplotr_1.18.0_master.tar.gz", repos=NULL, type="source")` command. I tried uninstalling & re-installing multiple time.

I checked the wiggleplotr.R from the `wiggleplotr_1.18.0_master.tar.gz` i downloaded, and I do not see any anno.colors & anno.label.size arguments in the PlotTranscript function (or in the whole script). 

Do you think this error may come from the wiggleplotr_1.18.0_master.tar.gz ? 

Thank you very much in advance,

Rémi

**Comment by wenweixiong** [comment]
Hi Romeo,

Thank you so much for reaching out.

Apologies, I have inadvertently shared the unmodified (original) wiggleplort package.

Please download the modified package here: http://datashare.molbiol.ox.ac.uk/public/wwen/wiggleplotr_1.18.0.tar.gz

And then install it using this line of code: install.packages("wiggleplotr_1.18.0.tar.gz", repos=NULL, type="source")

This modified package should now have the anno.colors and anno.label.size arguments.

Sean

**Comment by Romeo1-1** [comment]
I just tried and it works perfectly ! Thank you very much
