### ISSUE TITLE
AnnotateGenes.10x not annotating 'gene_type'

### ISSUE THREAD

**Issue by jesswhitts** [wenweixiong/MARVEL#6]
Hello, 

First of all, thanks for the great tool!

I am following the 10X tutorial you have posted. When running the function AnnotateGenes.10x, the gene_type annotations are not maintained, and are just listed as:

> table(marvel$gene.metadata$gene_type)
character(0) 
       17533 

Strangely though when I copy the code from "Script_DROPLET_02_PREPROCESS_1_AnnotateGenes.R", it runs perfectly fine:

> table(marvel$gene.metadata$gene_type)
IG_C_gene IG_C_pseudogene IG_V_pseudogene          lncRNA  protein_coding       TR_C_gene       TR_V_gene 
         1                       1                              1                            3666           13855                       6                         3 

I have tried re-installing the package and it has made no difference.
Unsure what the issue is, or if there even is an issue, just something to be aware of :)

Best,
Jess

**Comment by wenweixiong** [comment]
Hi Jess,

Thank you for reaching out :)

This issue has been fixed since version 2.0.1.

Please may you re-install the package from Github (not CRAN)?

library(devtools)
install_github("wenweixiong/MARVEL")
library(MARVEL)

Sean

**Comment by jesswhitts** [comment]
ah, sorted now. Thanks!
