### ISSUE TITLE
Unable to install wiggleplotr package

### ISSUE THREAD

**Issue by LenonaFan** [wenweixiong/MARVEL#7]
Hi,

It seems that there's something wrong with the link you offered to download the wiggleplotr package.

Could you please help to fix this?

Thanks!

**Comment by wenweixiong** [comment]
Thank you for reaching out.

I have updated the reposity link for the modified wiggleplotr package: 

https://drive.google.com/file/d/1eEkq1axQXynVifWanh9ACichIrJjyNfr/view?usp=share_link
