### ISSUE TITLE
Splicing event metadata

### ISSUE THREAD

**Issue by fpauler** [wenweixiong/MARVEL#8]
Hi,
I am very interested in your pipeline and currently I am implementing it for our data.
Thank you for preparing such detailed instructions, however I am running into an issue with rMATS.
I am using rMATS-turbo v4.1.0 that I got from here: https://rnaseq-mats.sourceforge.net/rmats4.1.0/index.html
I can run the rMATS analysis and get output files like: fromGTF.SE.txt, but I fail to find the "featureData.txt" files like SE_featureData.txt.
Do you have any idea what I am doing wrong?
Thank you very much for your support,
best,
Florian

**Comment by wenweixiong** [comment]
The rMATS outputs would been to be processed to match MARVEL's splicing nomenclature https://wenweixiong.github.io/Splicing_Nomenclature to generate the "featureData.txt" files. I will update MARVEL with the functions to do so in a few days time, and then I'll get in touch with you once I'm ready.

**Comment by fpauler** [comment]
thank you very much for your support with this issue!

**Comment by wenweixiong** [comment]
I have updated MARVEL by including the Proproces_rMATS function to convert rMATS splicing coordinates (fromGTF.*.txt) for MARVEL (*_featureData.txt). Demo scripts and data here: https://drive.google.com/file/d/1yv59wXhOZUmCB18VmSnOcFkmvLFURU7s/view?usp=share_link

Prior to running this function please re-install MARVEL from Github:

library(devtools)
install_github("wenweixiong/MARVEL")
library(MARVEL)

More info under "version 2.0.4" section of the MARLVE Github page: https://github.com/wenweixiong/MARVEL

Hope this helps :)
