### ISSUE TITLE
Is the tool available for snRNA data

### ISSUE THREAD

**Issue by longfeili5170** [wenweixiong/MARVEL#9]
Hi！

I am very interested in the tool, but the data I have is 10X multiome.
So I would like to know if I can use this tool to process snRNA data?
Looking forward to your reply.

Thanks!!!

**Comment by wenweixiong** [comment]
MARVEL is built for single-cell splicing analysis. For 10x multiome, I would recommend Signac (https://stuartlab.org/signac/articles/pbmc_multiomic.html). After which, if you're interested in splicing analysis, you may retrieve and format the relevant data from Signac and feed them into MARVEL. Input files format for MARVEL here: See "Input files" section of the tutorial https://wenweixiong.github.io/MARVEL_Droplet.html
